### ISSUE TITLE
Hotbar items stop working when moved to another slot

### ISSUE THREAD

**Issue by xDanub** [artulloss/Hotbar#11]
Any issues regarding pocketmine spoons will be disregarded and closed.
Make sure that you can produce the bug without any other plugins.

**Describe the bug**
When you have a hotbar and you have the locked-hotbar option disabled the item will work in the desired hotbar slot only. Then once moved to another slot it doesnt work, then once moved back to original spot it still doesnt work.

**To Reproduce**
1. Apply a hotbar
2. Disable locked-hotbar option in config
3. Use the item (mine was a command)
4. Move the item
5. Try to use the item again

**Expected behavior**
I expected the hotbar item to be able to be used whenever it is clicked regardless of the hotbar slot it is in when hotbar-lock is disabled

**Desktop (please complete the following information):**
 - API: 3.16.0
 - OS: Windows
 - Version 1.16.100

**Additional context**

**Comment by artulloss** [comment]
This was intended to work to prevent issues with having two of the same item. I'll implement a fix using nbt.

**Comment by xDanub** [comment]
Amazing, ty sir!

**Comment by xDanub** [comment]
@artulloss Is it possible to make an option for it to not clear inventory when you login aswell?

**Comment by artulloss** [comment]
I feel like your use case is not what this was intended for- this is for menus in like a lobby. Mind telling me what you're trying to do? If it's just commands to be clicked on items I suggest this plugin. https://github.com/TheAz928/ItemCommands

**Comment by xDanub** [comment]
Sorry I guess I was just pushing the limits of your plugin I guess. I was intending to use it as the plugin you linked is used. Thanks for the help. My discord is Danub#4689 if you'd like to hear about what I'm trying to do.

**Comment by artulloss** [comment]
Didn't work. Mine is adam#9876.

**Comment by xDanub** [comment]
whoops, lowercase D. Sent you a request. Solved the issue using https://github.com/TheAz928/ItemCommands and https://poggit.pmmp.io/ci/IceCruelStuff/SpawnWithItems/SpawnWithItems
