### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kingboydeve** [artulloss/Hotbar#15]
This plugin is'nt working in **Specified worlds**.

It's my hotbars config:
![Screenshot_۲۰۲۲-۰۷-۰۵-۱۱-۲۴-۰۴-۰۰۷_com android chrome](https://user-images.githubusercontent.com/101209290/177277237-c5656038-2cbb-4ee0-a331-dddb781d3af5.jpg)

It's my worlds config:
![Screenshot_۲۰۲۲-۰۷-۰۵-۱۱-۲۳-۵۵-۴۷۱_com android chrome](https://user-images.githubusercontent.com/101209290/177277316-33bb172e-a97c-4e83-8b70-696a6f968698.jpg)

This is a bug in my config or in your plugin?????
**HELP ME**

**Comment by artulloss** [comment]
Sorry for the very late response. Needed an attachment of the config, but as this plugin is used on at least one production server without issues, it's most likely an issue with your config.
