### ISSUE TITLE
Two items for Hotbaar

### ISSUE THREAD

**Issue by Mathz890** [artulloss/Hotbar#6]
Any issues regarding pocketmine spoons will be disregarded and closed.
Make sure that you can produce the bug without any other plugins.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - API: [e. g. 3.5.0]

**Additional context**

**Comment by Mathz890** [comment]
I can not put two objects in the Hotbar configuration

**Comment by artulloss** [comment]
Paste your configuration

**Comment by Hzste** [comment]
How can you add 2 hot bars on 1 world?

**Comment by artulloss** [comment]
You would setup one so it is registered to the world and have an item in that hotbar run the hotbar {hotbarName} {player} command to make the other hotbar appear
